#include <iostream>
#include <vector>
using namespace std;
//This program takes in a list of names separated by (,), (.), or (:)
//Should check for every name and if all names are spelled correctly
//The program will print the nonname words like "back row" 

vector<vector<string>> nameDB = {
    {"Alexis Andersen", "Alexander Arriola", "Adam Benton", "Andrew Boyd", "Alanna Boze", "Aaron Cerda", "Alexandra Chumley", "Andrew Coward", "Amyrah Doty", "Aidan Eliasson", "Aidan Forsey-Smerek", "Artin Ghamari", "Addison Gilbert", "Alexsys Gill", "Aaron Guo", "Aidan Gutierrez", "Andrew Ha", "Amanda Hangartner", "Ayden Harper", "Anika Hauser", "Avery Howard", "Armaan Jhangiani", "Aurora Khatibi Garrity", "Amanda King", "Ameenah Leigh", "Anissa Leigh", "Andre Lendi", "Andrea Lin", "Anthony Lucido", "Abigail Maemoto", "Aaron Martinez", "Arjun Mathew", "Aryana Mendoza", "Andre Meono", "Alice Min", "Alexander Pierce", "Adrian Poroj", "Alyssa Prado", "Alexis Randolph", "Aidan Regan", "Ashley Reynolds", "Anton Richard", "Ashley Schmid", "Avery Simonian", "AnnMarie Sorenson", "Angela Strong", "Anna Tom", "Audrey Tomasello", "Andrew Vasilion", "Aidan Wattson", "Alexandra Wescott", "Ashley Yi", "Arshia Youssefie", "Aaron Brandt", "Andrew Carpenter", "Aiden Chominsky", "Ariel Cooper", "Anne Sophie Corry", "Adam Demoner", "Alex Ewald", "Alexis Fox", "Allison Guo", "Ajuny Hansra", "Ashlyn Holcher", "Arianna Hutcheson", "Aliyah Jamerson", "Alycen Kim", "Annika Kissel", "Alex Klerman", "Avery Lahr", "Angie Lee", "Ava Lord", "Arman Mardani", "Ava McCoy", "Anne Miyashita", "Austin Mone", "Aidan O'Donnell", "Alexander Paulson", "Abigail Post", "Aliyana Rhemtulla", "Adrian Ridgely", "Adela Riggs", "Aeryn Rodney", "Alan Romero-Leon", "Alexander Rusich", "Alexandra Schoepke", "Amberly Seaburn", "Aprajita Singh", "Aidan Sun", "Alexandra Sverkounova", "Anna Terrell", "Asha Timm", "Ayla Torres", "Afton Walsh", "Ava Yang", "Aria Ahrar", "Angelina Aranda", "Aidan Beckman", "Amber Chen", "Alexis Choi", "Ava Coppola", "Alexandra Donell", "Alexa Dox", "Alex Forman", "Allison Furriel", "Andria Furriel", "Abigail Heffley", "Annika Hester", "Alaina Johnson", "Angelina Lazar", "Audri Lee", "Arshia Maleki", "Andrew Melcic", "Alexandria Mohammed", "Alina Montalvan", "Alyson Moulton", "Audrey Munro", "Audrey O'toole", "Aidan Olson", "Amarachi Onyeador", "Adrianna Ortega", "Alexandra Peckovich", "Alexander Ramirez", "Arvin Rod", "Alan Roofian-Akhavan", "Ainsley Schmitz", "Ava Sinfield", "Alanah Sparks", "Ava Stanczak", "Andreas Tempereau", "Anthony Tomasevic", "Anissa Vafadari", "Anthony Yoon"},
    {"Ben Alvarado Dia", "Bodi Brannen", "Bradley Brothers", "Brooke Cleveland", "Bryce Cooper", "Beau Demerjian", "Breaunna Garcia", "Brian Ha", "Beom Joon Kim", "Brett Olson", "Bradley Sharp", "Brooke Stiebel", "Benjamin Trotter", "Brooke Borden", "Brooklyn Coon", "Bella D Alfonso", "Bryce Ferraro", "Brianna Gianetto", "Benjamin Jorgensen", "Brianna Kunich", "Bridget Livingston", "Brendan Loo", "Brayden Lowe", "Benjamin Nolan", "Bence Peti-Peterdi", "Brooklyn Simpson", "Bradley Ballard", "Brooke Giordano", "Bridget Gormley", "Brandon Ku", "Beau Lai", "Bowen Moravek", "Brynn Ottolia", "Brennan Shaul"},
    {"Cyrus Abdo", "Callie Abeson", "Connor Appel", "Cameron Bond", "Chloe Boss", "Christian Burke", "Christian Cartwright", "Cameron Collier", "Casilda Corral Gutierrez", "Cole Dean", "Chloe Dowling", "Cameron Greene", "Cristen Haddad", "Claire Hardesty", "Cambell Harrigian", "Christian Hokama", "Candy Holguin", "Chaya Holyfield", "Carrie Knickrehm", "Cameron Lally", "Colin Lantz", "Chan Lee", "Claudia Lee", "Curtis Liu", "Carolina Martel", "Chloe Martin", "Chibueze Onyeador", "Christopher Peters", "Cassandra Pheiffer", "Christian Ramirez", "Charlotte Shook", "Charles Spivey", "Collin Stewart", "Conner Sullivan", "Charlotte Teets", "Caroline Tenney", "Chandler Trivell", "Christos Tsangaris", "Chayce Tulley", "Cole Welcher", "Calvin Amini", "Calvin Barnum", "Caroline Berry", "Chloe Blue", "Casey Cantella", "Charlotte Cicero", "Caiden Cunningham", "Carly Fitzpatrick", "Campbell Howard", "Coral Hugoboom", "Camila Jongsma", "Carson Kim", "Cindy Lanza", "Connor Mackey", "Carter Merchant", "Clark Michel", "Carissa Murray", "Caroline Paskus", "Connor Pinkerman", "Connor Ramsdell", "Cheridan Russell", "Charley Saalberg", "Christopher Salas", "Conrad Sanacore", "Charles Simpson", "Conor Steinbach", "Connor Storr", "Courtney Sugano", "Cassidy Virzi", "Carolyn Vogel", "Cole Balhan", "Charles Beuerlein", "Charles Dodge", "Caiden Falstrup-Finney", "Cate Fasoletti", "Charles Geniesse", "Claudia Goldsworthy", "Chandra Joy", "Caroline Kelliny", "Courtney Khan", "Caeden Kim", "Calissa Mayer", "Conner McDonald", "Casey Norman", "Connor Peters", "Charlotte Pluimer", "Cherise Stoll", "Courtney Stroud", "Charles Sullivan", "Christopher Wallace", "Cole Yamane", "Christine Yousefi", "Crystal Yousefi"},
    {"Daniel Amir", "Daniel Belzberg", "Dominic Bidondo-Yore", "Dominic Ciolino", "Davis Corman", "Devyn Hall", "Dylan Hassanzai", "David Headon", "Daniel Hess", "Devon McVicar", "Dylan Nelligan", "Dune Palmer", "David Perelmuter", "Dori Rich", "Daisy Robertson", "Dushan Samuela", "Deen Veera", "Delaney Bradley", "Delaney Burns", "Daniel Cohen", "David Jadin Comandante", "Dylan Delgado", "Dylan Hunter", "David Maemoto", "Dillon Moore", "Daniel Olvera", "Danielle Parker", "Dayanarah Villegas", "Dakota White", "Diane Anderson", "Dylan Bigley", "Daniel Chon", "Davis Donaldson", "Dakota Dwan", "Danielle Fullerton", "Donghao Guo", "Devin Jones", "Daniel Lowe", "Davryn McDuffie", "Doyle Nielsen", "Donald Olsen", "Damon Pourmohsen", "Dean Puckett", "Darren Shiao", "D'juan Strong", "Dominick Ungaro", "David Wingard", "David Zalmanovich", "Dylan Zar", "David Zavarella"},
    {"Elise Basic", "Elizabeth Campbell", "Eliana Denham", "Emily Drawer", "Ella Frost", "Emily Gesseck", "Emma Hill", "Ethan Hladek", "Ellen Hubbard", "Emily Katnic", "Ethan Kimmes", "Ethan King", "Elisa Liberati", "Emma Nelson", "Emma Saul", "Esa Shabazz", "Ethan Shanofsky", "Emma Shapiro", "Eric Sheng", "Elijah Simpson", "Emma St. Hilaire", "Elaina Truong", "Emily Typrowicz", "Ellie Van Wier", "Elijah Adams", "Emely Alvarenga", "Ellen Brandt", "Erick Chamnanpan", "Emma Conkling", "Erik Gressett", "Elizabeth Manth", "Ellis McConaughy", "Eden Paddock", "Emmet Paul", "Elysse Tansavatdi", "Erika You", "Ethan Eliasson", "Emma Fasoletti", "Ella Freebury", "Elijah Huang", "Ehinome Inegbenoise", "Emma Islava", "Elizabeth Kehrli", "Erin Kelly", "Emily Lee", "Erik Lee", "Eva Mayrose", "Emily Milam", "Elijah Munoz", "Ella Russo", "Emily Snider", "Eli Weiss-Schmidt", "Emily Zimet"},
    {"Fareed Ahmed", "Francisco Bonilla", "Fiona Calandrelli", "Finlay Kehrli", "Frank LaBreche", "Farinaz Osati", "Farah Dia", "Floyd Stott", "Fernando Chavez", "Faizan Jaffer", "Frances Kim"},
    {"Giulliana Ardon", "Grace Bernard", "Graysen Bradley", "Gabriela Collatos", "Griffin Colomer", "Gabriella Jonas", "Grace Liu", "George Mashy", "Gavin Peters", "Griffen Puhl", "Gavin Roberts", "Garrett Rudy", "Gabriel Silk", "Grant Thornburgh", "Gabrielle Wapner", "Grace Bonvechio", "Grace Borden", "George Bornheimer", "Gordon Boyle", "Gabriella Dorst", "George Furgis", "Grace Hsieh", "Grace Jonas", "Greger Joseph", "Grace Lucas", "Gabriela Munoz", "Greta Norris", "Gabriel Olvera", "Gavin Seaburn", "Griffin Tight", "Gabriella Brinderson", "Genevieve Cole", "Gabriel Covarrubias", "Gabriel Gill", "George Glor-Carrillo", "Grant Govel", "Gabrielle Grillo", "Grace Gulcher", "Grace Hebert", "Gabriel Karmelich", "Garren Rizzo", "George Steele", "Gavin Steenolsen", "Grace Trester", "Grant Walther"},
    {"Henry Boyle", "Hunter Dunlavey", "Hailey Fitt", "Harmony Ishikawa", "Hanna Karnes", "Hayden Kharrazi", "Hunter Mackenzie", "Hannah Nenadic", "Holly Stiebel", "Hana Tomizawa", "Hallie Umrarong", "Hannah Allen", "Hannah Baetge", "Heath Bray", "Hallie Emery", "Hannah Goharian", "Helena Mantikas", "Hudson Parks", "Harper Skeie", "Haeley Wertz", "Hudson Wesley", "Henry Carr", "Hayden Fu", "Hayden Greene", "Henry Huss", "Hayleigh Liu", "Hayleigh Lui", "Heather McClung", "Halie Moore", "Hudson Wolfe", "Hannah Ytterboe"},
    {"Ian Blanco", "Iruka-Dara Chidi", "Ifeoluwa Ibraheem", "Ian Kim", "Isabella Martinez", "Isabella Piccirillo", "Isaiah Thompson", "Isabella Bezelj", "Isabella Brannan", "Isabella Farrow", "Isabella Firmani", "Isabella Kim", "Ian Shitabata", "Ian Thompsen", "Isabella Hokama", "Isabella McPherson"},
    {"Jack Allegaert", "Jasper Belliveau", "Jaden Bigley", "Jaden Camel", "Jim Campbell", "Joseph Chelebian", "Jack Correa", "Julianna Covarrubias", "Julian Dixon", "Jadon Douglas", "Jenna Fitzpatrick", "Jacob Friedman", "John Granick", "Jack Griego", "Joshua Houlbrooke", "Jennifer Kamholz", "Juliette Koepke", "Justin Koepke", "Jack LaPlant", "John Mac Menamie", "Jessica Majka", "Joze Marinkovic", "John Maurizio", "Jackson McKeeve", "Joelle Montelongo", "Jessica Ottaway", "John Padian", "John Perry", "Justin Sohn", "Jake Spivey", "Jingdi Tan", "Jonathan Walter", "Jon Ward", "Jack White", "Jack Yang", "John Adeani", "Jasmine Alagoz", "Joseph Dalrymple", "Jake Danon", "Jack Davis", "Joshua Diokno", "Jack Donell", "Jantzen Ebreo", "Jake Fogle", "Jenna Gallo", "Joseph Hargrove", "John Helton", "Jeremy Joke", "John Kahrs", "Jackson Karlitz", "John Klarin", "Jake Koyama", "Jared Kramer", "Jacqueline Lanes", "Jillian Lawson", "Jenna Leone", "Joaquin Lugo", "Jessica Mabry", "Justin Mabry", "Jillian Martz", "Jack Mavar", "James Maxwell", "Joseph Miramontes", "Jordan Nelson", "John O'Connor", "Jose Ocampo", "Jenna Peterson", "Joi Ramirez", "Jamie Robertson", "Jonathan Ross", "Joseph Ryan", "Juliana Santich", "Jonathan Shier", "Julia Soll", "Jonathan Su", "Jack Tomlinson", "Johan Van Wier", "Jace Viramontes", "John Warner", "Jacob Ambris", "Jack Bowen", "Jaury Burke", "Joseph Calvagna", "Joseph Chontos", "Jenna Chow", "Jonathan Chu", "Julia Cohen", "James Cook", "Joseph Di Leva", "Jack Dibernardo", "Johannes Eberhart", "Jack Flanagan", "Joey Gallardo", "Jillian Gibson", "James Happy", "John Harris", "Jason Hong", "Jonah Jones", "Joshua Jun", "Jordan Kapner", "Jacqueline Lane", "Janna Lee", "Joshua Martin", "Jake McDonald", "Jake Milam", "Joshua Munoz", "Jahzara Nash", "Joseph O'connor", "Jett Palmer", "Jennifer Ramirez", "Jason Roah", "Joseph Saputo", "Jacqueline Skoblar", "Jason Soto", "Jake Tom", "Jacob Trujillo", "Jake Typrowicz", "John Wilhem", "Jake Yamane"},
    {"Katya Arencibia", "Kamal Baker", "Kevin Cross", "Kapilaksha Dheeriya", "Kevin Ghaffari", "Kaylie Harley", "Katelyn Hart", "Kelsey Hatamiya", "Kaycee Hong", "Kaydee Hong", "Katherine Hoyne", "Kiley Keenan", "Kristopher Kuerten", "Kaylin Lee", "Kylie McElroy", "Kevin McGibbon", "Kyla McLay", "Kai Tristan Mohl", "Kumiko Nagata", "Kevin Rahman", "Karl Velazquez", "Koa Vetterlein", "Kevin Chen", "Kale Chominsky", "Kate Dean", "Kailey DeHaro", "Kylie Freeland", "Kendall Galosic", "Katherine Jorczak", "Kyle Kan", "Kyra Kaya", "Katherine Keough", "Kenneth Knapp", "Kiyomi Komatsu", "Kaia Modica", "Kelly Rasmussen", "Karen Shinzawa", "Kara Shreckengast", "Kate Spaulding", "Katarina Stanojevich", "Kiera Stone", "Kai Teshima", "Kalina Teshima", "Keira Wang", "Kahealani Carvalho", "Katherine Choi", "Kyle Cooper", "Kelly Donahue", "Kharianna Gracie", "Kayla Hirt", "Katherine Hoover", "Konstantine Katona", "Kieran Kearns", "Korinna Kuerten", "Katelynn Lannon", "Katherine Mandala", "Kenzi McLay", "Kate Moore", "Kendra Oconnor", "Katiana Robles", "Kyra Schmid", "Kaitlyn Tarakji", "Kayla Thompson", "Kelsey Turnbull", "Kaia Van Buren", "Kekoa Van Scoyoc", "Karsten Wanke", "Kendall Ward", "Kylie Welcher", "Kiley Wynn"},
    {"Lyndsey Alfaro", "Liam Bohner", "Lance Cleveland", "Lucas Everhart", "Lauren Feingold", "Leilani Fonoimoana", "Leah Frka", "Laila Gallardo", "Lauren Hammond", "Lily Hamson", "Luke Hassanzai", "Luke Hobus", "Lucas Hong", "Laria Koncius", "Lauren Larking", "Leonard Liang", "Lucas Mattera", "Lisa Miao", "Lauren Naehu", "Landon Ota", "Luc Rettberg", "Lainey Cote", "Leah Glenn", "Lauren Kim", "Laura Maurizio", "Lindsey Metcalfe", "Lilly North", "Luke Stiebel", "Lily Tarica", "Lauren Thompson", "Lauren Underhill", "Luka Ardon", "Luca Barron", "Leah Buenrostro", "Lourdes Bury", "Lucas Coleman", "Landon Corman", "Logan Davis", "Lucas De Leon", "Luca Dileva", "Lucia Eaton", "Lucas Farrow", "Logan Hill", "Lily Kresser", "Lucas Lees", "Lily Lynch", "Laylah Marron", "Luke Martoccia", "Logan Nelson", "Leonardo Puccio", "Luke Rafijah", "Lucia Ruiz", "Leah Stubblebine", "Lindsay Yaros"},
    {"Michael Artino", "Maria Cabanas Zawadzky", "Maxwell Chas", "Meera David", "Mia Dellovade", "Meiers Dixon", "Morgan Fresch", "Matthew Frey", "Marina Gil Alcon", "Madison Grant", "Meagan Hendershot", "Maleha Innocent", "Morgan Irvine", "Matthew Kang", "Mark Lee", "Max Leeds", "Matthew Liang", "Marina Lugliani", "Matthew Maes", "Michael Malone", "Mia Marco", "Michael McBride", "Margaret McLeod", "Michael Mitsanas", "Michael Nagy", "Marko Nikoletic", "Megan O'Brien", "McKenzie Olsen", "Mykiah Plummer", "Mateo Poncia", "Maja Rancic", "Maya Roberson", "Mackenzie Shannon", "Mikayla Smith", "Megan Trainotti", "Mia Vafadari", "Maya Whitcomb", "Mackenzie Whitehead", "Meg Yoshida", "Maxwell Zarchy", "Melina Bakopoulou", "Mia Beresford", "Makenna Brannen", "Matthew Carroll", "Matthew Cartmill", "Mariah Chase", "Macarena Cuesta", "Milad Eghbali", "Maximilian Endelman", "Mathieu Fernandez", "Makena Fine", "Mia Fitzpatrick", "Matthew Francis", "Michael Guirgis", "Myles Hasegawa", "Milana Herrera", "Mason Jahelka", "Michael Kwon", "Mackenzie Lambertus", "Mirna Larios", "Mia McCauley", "Max Mendel", "Maxwell Merritt", "Matthew Olson", "Marinna Pisano", "Maggie Puhl", "Maya Sanacore", "Marjorie Say", "Mason Self", "Madeline Smith", "Melody Soroosh", "Michael Sprengel", "Mark Steburg", "Morgan Tomaro", "Matthias Yee", "Markus Aguirre", "Matthew Basha", "McKenna Butcher", "Mia Castillo", "Maxwell Colomer", "Mafalda Corral", "Madeline Delana", "Matthew Di Leva", "Matthew Farnsworth", "Mark Guggenheim", "Mia Harley", "Melanie Harris", "Miles Hong", "Minji Kang", "Mischa Kharrazi", "Maxwell Larkin", "Matthew Madrid", "Maya Merchant", "Mallory Meyer", "Matthew Mihelich", "Madison Miller", "Margaret O'Hern", "Megan Ocasio", "Marco Popovich", "Marco Rall Boardman", "Marielle Sandler", "Martin Scholz", "Melanie Tilles", "Megan Walsh", "Matthew Warter", "Madeline Weatherly", "Madison Wendel", "Mikayla Wurzer"},
    {"Nilaab Ahmadi", "Nicholas Baumann", "Nolan Brandt", "Nicole Chung", "Natalie Diaz", "Nicholas Hirt", "Nima Izadi", "Noah Lin", "Nicole Liontos", "Nikolaos Mantikas", "Nicholas Michaels", "Nathanael Nam", "Natalia Pope", "Nicole Rasmussen", "Natalie Reyes", "Noemi Ruelas", "Nikole Rugnetta", "Nicole Russo", "Natasha Stein", "Nathan Stein", "Natalie Stubblebine", "Nikita Swatek", "Nicholas Waisman", "Nicholas Abbasi", "Nicolas Calvert", "Natalie Chrone", "Niall Collins", "Natalia Huntington", "Nefise Kocak", "Nathaly Lizarraga", "Nevin Mann", "Nicholas Semmer", "Noah Wahl", "Nicolas Wright", "Natalie Ying", "Niko Adoric", "Nathan Blakey", "Nicholas Bozanic", "Nadia Cerda", "Nicholas Cosgrove", "Nicholas Dalrymple", "Neela David", "Nathan Dimacali", "Natalie Ferin Tholan", "Nicholas Finazzo", "Nicholas Gruninger", "Natalie Hong", "Naomi Kao", "Nico Lofty", "Nicholas Mantikas", "Noor Mathew", "Nathan Reinhart", "Nicolas Sanchez", "Natalee Soroosh", "Nicholas Stiebel", "Nika Susnjar", "Nathan Young-Nichols"},
    {"Owen Ladinig", "Olivia Malit", "Olivia Hecker", "Omeed Jahromi", "Owen Park", "Owen Brown", "Owen Chas", "Owen Griffiths", "Owen Hong", "Oscar Park", "Olivia Schnel"},
    {"Paolo Brinderson", "Patricio Cabagna", "Peyton Eberhard", "Paige Foster", "Parker Fry", "Pili Marco", "Peter Mirich", "Paige Porter", "Phillipe Wiederkehr", "Parker Zane", "Payton Ahn", "Paolo Bahrami", "Paris Dunlavey", "Paige Forte", "Paige Greenwood", "Page Jones", "Philip Melcic", "Paige Roach", "Paige Shin", "Peyton Brusick", "Patrick Hwang", "Peter Kraemer", "Parham Seyedshakeri"},
    {"Quentin Ruiz"},
    {"Rachel Allen", "Ryan Anderson", "Rebecca Aycock", "Ryan Baeza", "Rodrigo Boixo", "Rachel Bond", "Rhett Borda", "Ryan Bozanic", "Ryan Choi", "Richard Criley", "Ra'nya Crowder", "Rayanne Fadich", "Rhys Hendershot", "Ryan Hori", "Rebecca Kim", "Ryann Levendusky", "Ronald Lockwood", "Robert Marshall", "Rowan Moore", "Ryan Olarte", "Rachel Post", "Ryan Samani", "Riley Skinner", "Ripley Uyeda", "Ren Criss", "Ryan Hetchler", "Riley Lampe", "Riley Maguire", "Rosemary Martin", "Rhyan Nguyen", "Royce Relatores", "Ryan Roche", "Rei Takarai", "Reese Tillson", "Ronan Volman", "Rylee Wahl", "Ricardo Alexander", "Ryan Foley", "Rudi Johnson", "Rowan Klein", "Reese Levendusky", "Rider Mavar", "Raymond Moll", "Riko Negishi", "Riley Radovich", "Roslyn Tauvaa", "Ryan Wilson"},
    {"Sarah Baetge", "Sophia Brborich", "Samantha Chelf", "Shay Desai", "Sofia Fasoletti", "Sophie Geniesse", "Sarah Jun", "Stephen Kastelan", "Sofia Katzaroff", "Samantha Laurin", "Spencer Levin", "Samuel Levine", "Sarah Liu", "Sydney Lyle", "Shannon Lynch", "Stetson Martz", "Sydney Merchant", "Sara Metcalfe", "Samuel Miller", "Shaya Moayedi", "Sydney Naya", "Simone Ochalek", "Savannah Peden", "Shelby Ponce", "Shawnee Prieto", "Sarah Rancic", "Samuel Rohde", "Sayan Simanian", "Sydney Singh", "Shon Stallings", "Sofia Yarymovych", "Sophia Aguirre", "Shayli Atashi", "Sydney Baker", "Sarah Cartmill", "Sasha Chehrzadeh", "Sophia Cline", "Sean Conlon", "Sophia Cuyler", "Stephen DuVernet", "Sofia Fateeva", "Sarah Giller", "Shaela Hart", "Suzanne Jellison", "Steven Kaufman", "Savannah Krieger", "Sophia MacAller", "Spencer MacLeay", "Sam Malekzadeh", "Stella McKay", "Samuel Moore", "Sophia Norris", "Sophia Rodriguez", "Sebastian Schoepke", "Sky Shaw", "Scott Shimoyama", "Samantha Skeoch", "Sophie Tangalakis", "Spencer Tran", "Sean Wilson", "Sarah Austin", "Sydni Bednarek", "Samuel Bonner", "Stuart Canario", "Sean Cosgrove", "Sabrina Fair", "Sydnie Fuchs", "Sofia Goldblatt", "Sydney Goodrich", "Sophie Ray Harrah", "Skylar Hartman", "Sasha Hayes-Pleasant", "Sean Hetrick", "Sang Hee Jun", "Sofia Kalem", "Shay Lennemann", "Scarlett Martz", "Suhayb Mirza", "Sharlize Moayedi", "Sophia Murillo", "Steven Nagy", "Sierra Namvari", "Sarah Park", "Savanna Pierson", "Sophia Potter", "Samuel Rokaw", "Sharlena Sarmast", "Sarah Shah", "Sara Silvestri", "Sarah Simon", "Sean Slingsby", "Siena Snure", "Skylor Sun", "Sophia Ticknor", "Salvatore Traina", "Steel Weiss", "Sofia Zavarella"},
    {"Tyler Bagley", "Trace Basich", "Talia Blair", "Troy Burad", "Tyler Ewald", "Tor Gasteiger", "Trent Giacalone", "Tatiana Grimes", "Talia Hajjar", "Taylor Hirsch", "Thomas Lercari", "Tiana Mann", "Talia Patti", "Tomoi Stapleton", "Toby Stoler", "Taylor Stroud", "Tyler Colaruotolo", "Tessa Dontscheff", "Talon Gutierrez", "Toni Hagan", "Tyler Ljubic", "Tristan Messerli", "Tyler Royes", "Trystan Sheldon", "Troy Takahashi", "Troy Villa", "Tristan Wattson", "Tarick Ahmed", "Tanner Bagley", "Tara Bharadia", "Tony Califano", "Tyler Campbell", "Tony Cha", "Tiffany Chang", "Tingyi Cui", "Tristan Drake", "Tatum Lane", "Thomas Lapine", "Thomas Lee", "Tatiana Lindahl", "Tara Lofty", "Taylor Malinofsky", "Tali McLay", "Theodore Schipper", "Trevor Seaburn", "Thomas Underhill"},
    {},
    {"Vance Arenstein", "Vincent Furriel", "Victoria Moll", "Vidyuth Thattai", "Vince Villasenor", "Vikesh Dheeriya", "Violet Fermanian", "Vanessa Geich", "Viviana Hsiao", "Vincent Lamberti", "Violet Peer", "Vanessa Tran", "Veronica Waters", "Van Borda", "Vivian Chan", "Vincent Chor", "Valentina Duran Oris De Roa", "Valentina Gardner", "Vaughn Kissel"},
    {"Williams Criley", "William Engstrom", "Whitney Todosiev", "Willow Wollman", "William Wong", "William Bray", "William Kirk", "William Mulkey", "William Sasaki", "William Smart", "William Welsh", "William Bengston", "William Hirai", "William Perry", "William Rizzo", "Wylder Wollman"},
    {"Xander Chang"},
    {"Yoonseo Yi"},
    {"Zoey Belliveau", "Zachary Huang", "Zachary Kakazu", "Zoe Klein", "Zachary Dawson", "Zoe Dearborn", "Zoe Hutchins", "Zachary Pearce", "Zachary Schmidt", "Zoe Shafiezadeh", "Zackary Smith", "Zen Vibhakar", "Zacharia Ahmadi", "Zusan Hu", "Zachary Moore", "Zoe Ruehr"}
};
/*vector<vector<string>> nameDB = {
    {"Aaron Guo"},
    {},
    {"Cameron Greene"}
};*/

vector<string> getNames(string list) { //separates all the names from each other

    vector<string> names = {};
    string currentName = "";
    for(int i = 0; i < list.size(); i++) {
        if(list.at(i) == ',' || list.at(i) == ':') {
            names.push_back(currentName);
            currentName = "";
            i++;
        }
        else if(list.at(i) == '.' && !(currentName == "Mr" || currentName == "Mrs" || currentName == "Ms")) {
            names.push_back(currentName);
            currentName = "";
            i++;
        }
        else
            currentName += list.at(i);
    }
    names.push_back(currentName);

    return names;

}

void checkSpelling(vector<string> names) { //compares each name to the names in the database

    cout << "Wrong Names: " << endl;
    for(int i = 0; i < names.size(); i++) {

        string currentName = names.at(i);
        int firstLetter = (int)(currentName.at(0));
        if(firstLetter < 97)
            firstLetter -= 65;
        else
            firstLetter -= 97;

        if(firstLetter < 26) {

            bool nameFound = false;
            for(int j = 0; j < nameDB[firstLetter].size(); j++) {
                if(currentName == nameDB[firstLetter][j]) {
                    nameFound = true;
                    break;
                }
            }
            if(!nameFound)
                cout << currentName << endl;

        }

    }

}

int main() { //driver

    string list;
    getline(cin, list);
    vector<string> names = getNames(list);
    checkSpelling(names);

    /*for(int i = 0; i < names.size(); i++) {
        cout << names.at(i) << endl;
    }*/

}