#include <iostream>
#include <vector>
#include <windows.h>
using namespace std;
//This program takes in a list of names separated by (,), (.), or (:)
//Should check for every name and if all names are spelled correctly
//The program will print the nonname words like "back row" 

vector<vector<string>> nameDB = {
	{"Aria Ahrar", "Aaryan Angadi", "Athanasios Angouras", "Angelina Aranda", "Alexander Arriola", "Aidan Beckman", "Adam Benton", "Alessandro Bonvechio", "Andrew Boyd", "Alanna Boze", "Aaron Brandt", "Ashley Buffone-Swift", "Alexandros Cacos", "Ava Califano", "Andrew Carpenter", "Aaron Cerda", "Amber Chen", "Alexis Choi", "Aiden Chominsky", "Anthony Chor", "Alexandra Chumley", "Avonlea Coon", "Ariel Cooper", "Ava Coppola", "Anne Sophie Corry", "Andrew Coward", "Alexandria De Armas", "Alyssa Delgado", "Adam Demoner", "Alexandra Donell", "Amyrah Doty", "Alexa Dox", "Aidan Eliasson", "Alex Ewald", "Andre Fleuette", "Alex Forman", "Aidan Forsey-Smerek", "Alexis Fox", "Abigail Frauman", "Allison Furriel", "Andria Furriel", "Aksh Garg", "Amelie Gavino", "Artin Ghamari", "Addison Gilbert", "Alexsys Gill", "Anthony Goldberg", "Adan Gomez", "Aaron Guo", "Allison Guo", "Aidan Gutierrez", "Andrew Ha", "Ashlee Habif", "Amanda Hangartner", "Adam Hardesty", "Ava Harkavy", "Ayden Harper", "Alexander Hassanein", "Anika Hauser", "Abigail Heffley", "Aiden Hendershot", "Andrew Hirai", "Alexa Hirsch", "Alana Holcher", "Ashlyn Holcher", "Ashton Horeczko", "Avery Howard", "Arianna Hutcheson", "Aliyah Jamerson", "Ashlyn Jensen", "Armaan Jhangiani", "Alaina Johnson", "Alexa Johnson", "Austin Jones", "Ava Keshtkar", "Aurora Khatibi Garrity", "Alycen Kim", "Amanda King", "Annika Kissel", "Alex Klerman", "Avery Lahr", "Angelina Lazar", "Alex Lee", "Angie Lee", "Audri Lee", "Ameenah Leigh", "Anissa Leigh", "Andre Lendi", "Antonio Liberati", "Andrea Lin", "Ava Lord", "Anthony Lucido", "Abigail Maemoto", "Arshia Maleki", "Arman Mardani", "Aaron Martinez", "Arjun Mathew", "Ava McCoy", "Andrew Melcic", "Anthony Mendoza", "Aryana Mendoza", "Aaron Meono", "Alice Min", "Anne Miyashita", "Austin Mone", "Alina Montalvan", "Alyson Moulton", "Audrey Munro", "Alexander Naehu", "Aidan O'Donnell", "Aidan Olson", "Amarachi Onyeador", "Adrianna Ortega", "Audrey O'Toole", "Amalie Ounanian", "Aaron Paik", "Alexander Paulson", "Anna Peti-Peterdi", "Alexander Pierce", "Angelina Pierce", "Adrian Poroj", "Abigail Post", "Alyssa Prado", "Alexander Ramirez", "Alexis Randolph", "Aidan Regan", "Ashley Reynolds", "Anton Richard", "Adela Riggs", "Austin Roach", "Arvin Rod", "Aeryn Rodney", "Alan Romero-Leon", "Alexander Rusich ", "Arman Savar", "Ashley Schmid  ", "Ainsley Schmitz", "Alexandra Schoepke", "Alexander Schumy", "Amberly Seaburn", "Arianna Sheldon", "Aidan Shen", "Avery Simonian", "Ava Simpson", "Aprajita Singh", "Anne Slingsby", "Aeris So", "Abigail Song", "AnnMarie Sorenson", "Ava Stanczak   ", "Angela Strong", "Aidan Sun", "Alexandra Sverkounova", "Andreas Tempereau", "Anna Terrell", "Asha Timm", "Audrey Tomasello", "Anthony Tomasevic", "Ayla Torres", "Angelo Ungaro", "Anissa Vafadari", "Andrew Vasilion", "Abigail Waisman", "Afton Walsh", "Aidan Wattson", "Alexandra Wescott", "Alaina Wong", "Alexander Yancheson", "Ava Yang", "Ashley Yi", "Anthony Yoon", "Arshia Youssefie"},
	{"Ben Alvarado Dia", "Brette Andrews", "Bradley Ballard", "Brooke Borden", "Bodi Brannen", "Benicio Brborich", "Bradley Brothers", "Brian Carroll", "Brooke Cleveland", "Braden Colli", "Brooklyn Coon", "Bryce Cooper", "Bella D Alfonso", "Beau Demerjian", "Bryce Ferraro", "Breaunna Garcia", "Benjamin Gardner", "Brianna Gianetto", "Brooke Giordano", "Bridget Gormley", "Brian Ha", "Benjamin Hawk", "Barsam Jaberi", "Benjamin Jorgensen", "Beom Joon Kim", "Brandon Ku", "Brianna Kunich", "Beau Lai", "Brendan Loo", "Brayden Lowe", "Bella Luciano", "Brian Mackenzie", "Braydan Maloney", "Braden Matthews", "Bowen Moravek", "Benjamin Nolan", "Brendan O'Donnell", "Brett Olson", "Brynn Ottolia", "Brian Park", "Bence Peti-Peterdi", "Bradley Sharp", "Brennan Shaul", "Brooklyn Simpson", "Brooke Stiebel", "Benjamin Trotter", "Benjamin Yousif"},
	{"Cyrus Abdo", "Callie Abeson", "Calvin Amini", "Connor Appel", "Cole Balhan", "Caitlyn Barley", "Calvin Barnum", "Caroline Berry", "Charles Beuerlein", "Chloe Blue", "Cameron Bond", "Chloe Boss", "Connor Bradley", "Cash Brannen", "Cecilia Brown", "Casey Cantella", "Christian Cartwright", "Chloe Choi", "Charlotte Cicero", "Cameron Collier", "Cayden Cooper", "Casilda Corral Gutierrez", "Caiden Cunningham", "Cole Dean", "Claudia Dineen", "Charles Dodge", "Chloe Dowling", "Caiden Falstrup-Finney", "Cate Fasoletti", "Carly Fitzpatrick", "Camden Friedman", "Charles Geniesse", "Cameron Gherardi", "Claudia Goldsworthy", "Carson Goring", "Cameron Greene", "Cristen Haddad", "Claire Hardesty", "Cambell Harrigian", "Cynthia Ho", "Christian Hokama", "Candy Holguin", "Chaya Holyfield", "Campbell Howard", "Craig Howell", "Coral Hugoboom", "Camila Jongsma", "Chandra Joy", "Caroline Kelliny", "Caden Kendall", "Courtney Khan", "Caden Kim", "Caeden Kim", "Carson Kim", "Claire Kirk", "Carrie Knickrehm", "Cemal Kocak Bonavota", "Christopher Lachowicz", "Cameron Lally", "Colin Lantz", "Cindy Lanza", "Chan Lee", "Claudia Lee", "Connor Lewis", "Chaeyoung Lim", "Clarence Lin", "Curtis Liu", "Catherine Lucas", "Connor Mackey", "Curran Maguire", "Christian Marr", "Carolina Martel", "Chloe Martin", "Calissa Mayer", "Conner McDonald", "Ciara McGovern", "Cayden McGuire", "Conor McKenna", "Christa McKnight", "Christopher McNeill", "Carter Merchant", "Clark Michel", "Carson Moore", "Carissa Murray", "Casey Norman", "Carlo Onorato", "Ciro Onorato", "Chibueze Onyeador", "Caroline Paskus", "Christopher Peters", "Connor Peters", "Cassandra Pheiffer", "Connor Pinkerman", "Charlotte Pluimer", "Christian Ramirez", "Connor Ramsdell", "Carson Rhodes", "Cheridan Russell", "Charley Saalberg", "Christopher Salas", "Conrad Sanacore", "Charlotte Shook", "Charles Simpson", "Charlotte Smalley", "Cole Spanjol", "Christos Spanos", "Charles Spivey", "Conor Steinbach", "Collin Stewart", "Cherise Stoll", "Connor Stortz  ", "Courtney Stroud", "Colin Stuart", "Courtney Sugano", "Charles Sullivan", "Conner Sullivan", "Charlotte Teets", "Caroline Tenney", "Chandler Trivell", "Christos Tsangaris", "Christos Tseperis", "Chayce Tulley", "Christopher Vasey", "Cassidy Virzi", "Carolyn Vogel", "Cole Vranich", "Christopher Wallace", "Cole Welcher", "Christine Xie", "Cole Yamane", "Camille Ying"},
	{"Daniel Abudy", "Donya Ahmady", "Daniel Amir", "Diane Anderson", "Daniel Belzberg", "Dominic Bidondo-Yore", "Dylan Bigley", "Delaney Bradley", "Deegan Brand", "Delaney Burns", "Daniel Chon", "Donovan Cicero", "Dominic Ciolino", "David Jadin Comandante", "Davis Corman", "Duke DeLeo", "Dylan Delgado", "Davis Donaldson", "Dakota Dwan", "Dylan Ferraro", "Danielle Fiamengo   ", "Danielle Fullerton", "Dominick Gabriel", "Diego Gomez", "Donghao Guo", "Devyn Hall", "Dylan Hassanzai", "David Headon", "Daniel Hess", "Dylan Hunter", "Devin Jones", "David Kim", "David Kohn", "Dolan Leman", "Daniel Lowe", "David Maemoto", "Davryn McDuffie", "Devon McVicar", "Dylan Michaelis", "Dillon Moore", "Dylan Nelligan", "Doyle Nielsen", "Donald Olsen", "Daniel Olvera", "Dyton Orr", "Derek Ottaway", "Dune Palmer", "Danielle Parker", "David Perelmuter", "Daniel Peresztegi", "Damon Pourmohsen", "Dean Puckett", "Dori Rich", "Daisy Robertson", "Daniela Rusich", "Dushan Samuela", "Delaney Shannon", "Darren Shiao ", "Daniel Stender", "David Su", "Derek Su", "Dashiell Tyler", "Dominick Ungaro", "Deen Veera", "Dayanarah Villegas", "Daisy Warner", "David Wells", "Dakota White", "David Wingard", "David Zalmanovich", "Dylan Zar", "David Zavarella", "Dylan Zavarella"},
	{"Elijah Adams", "Ethan Aleixo", "Emely Alvarenga", "Erick Banks", "Elise Basic", "Emily Boyd", "Ellen Brandt", "Elizabeth Campbell", "Erick Chamnanpan", "Eunseo Choo", "Emma Conkling", "Ella Contreras", "Edward Correa", "Eliana Denham", "Emily Drawer", "Ethan Eliasson", "Emma Fasoletti", "Ella Freebury   ", "Ella Frost", "Emily Gesseck", "Erik Gressett", "Elaria Guirgis", "Emily Heinze", "Eric Hernandez", "Emma Hill", "Ethan Hladek", "Enna Hosoi", "Elijah Huang", "Ellen Hubbard", "Emma Islava", "Emily Katnic", "Elizabeth Kehrli", "Erin Kelly", "Erin Kessel", "Ethan Kimmes", "Ethan King", "Eleni Klostrakis", "Elliot Langston", "Emily Lee", "Erik Lee", "Eugene Lee", "Elisa Liberati", "Elizabeth Manth", "Eva Mayrose", "Emily Milam", "Eric Mulkey", "Elijah Munoz", "Emma Nelson", "Eden Paddock", "Emmet Paul", "Elayna Pope", "Emma Post", "Estevan Rowe", "Ella Russo ", "Emma Saul ", "Esa Shabazz", "Ethan Shanofsky", "Ella Shapiro", "Emma Shapiro", "Eric Sheng", "Elijah Simpson", "Emily Snider", "Emma St. Hilaire", "Elysse Tansavatdi", "Evan Teshima", "Elaina Truong", "Emily Typrowicz", "Eto Uchiyama", "Ellie Van Wier", "Eli Weiss-Schmidt", "Emi Yamamori", "Eva Yancheson", "Erika Yiu", "Emily Zimet"},
	{"Fareed Ahmed", "Forest Bates", "Francesca Bidondo-Yore", "Francisco Bonilla", "Fiona Calandrelli", "Fernando Chavez", "Farah Dia", "Faizan Jaffer", "Finlay Kehrli", "Frances Kim", "Frank LaBreche", "Fiona MacDonald", "Ford Mattera", "Farinaz Osati", "Floyd Stott", "Frances Stott  ", "Flora Wells"},
	{"Gabriela Alvarez", "Giulliana Ardon", "Gianni Battaglia", "Grant Beranek", "Grace Bernard", "Gia Bohorquez", "Grace Bonvechio", "Grace Borden", "George Bornheimer", "Gordon Boyle", "Graysen Bradley", "Gabriella Brinderson", "Gabriel Canet", "Genevieve Cole", "Gabriela Elizabeth Collatos", "Griffin Colomer", "Gabriel Covarrubias", "Gabriella Di Camillo", "George Furgis", "Griffin Gallien", "Gabriel Gill", "George Glor-Carrillo", "Grant Govel", "Gabrielle Grillo", "Grace Gulcher", "Gabrielle Guzman", "Grace Hebert", "Gabriella Jonas", "Grace Jonas", "Gabriel Karmelich", "Grant Kraemer", "Gavin Kresser", "George LaBreche", "Graydon Leong Kaye", "Grant Libeu", "Grace Liu", "Grace Lucas", "George Mashy", "Gavin McKay", "Grace Monroy", "Gavin Montgomery", "Grace Moore", "Gabriela Munoz", "Greta Norris", "Gabriel Olvera", "Gavin Peters", "Griffen Puhl", "Garren Rizzo", "Gavin Roberts", "Garrett Rudy", "Gavin Seaburn", "Grace Segura Mendoza", "Ganav Siddha", "Gabriel Silk", "George Steele", "Gavin Steenolsen", "Gavin Steuerwald", "Gordon Teuber", "Grant Thornburgh", "Griffin Tight", "Grace Trester", "Grant Walther", "Gabrielle Wapner"},
	{"Hollister Alexander", "Hannah Allen", "Hannah Baetge", "Henry Boyle", "Heath Bray", "Henry Carr", "Hunter Dunlavey", "Hayden Edwards", "Hallie Emery", "Hailey Fitt", "Hayden Fu", "Hannah Goharian", "Hayden Greene", "Henry Huss", "Harmony Ishikawa", "Hanna Karnes", "Hayden Kharrazi", "Hayleigh Liu", "Hunter Mackenzie", "Helena Mantikas", "Heather McClung", "Halie Moore", "Harrison Moore", "Hannah Nenadic", "Hudson Parks", "Harrison Plimmer", "Hunter Ruiz", "Harper Skeie", "Haleigh Smith", "Holly Stiebel", "Hana Tomizawa", "Hallie Umrarong", "Hugo Wayner", "Hudson Wesley", "Hunter Winkler", "Hudson Wolfe", "Hana Wright", "Hannah Ytterboe"},
	{"Isabella Bezelj", "Ian Blanco", "Isabella Brannan", "Iruka-Dara Chidi", "Isabella Cordi", "Ione Eaton", "Isabella Farrow", "Isabella Firmani", "Isabella Franco", "Isabella Hokama", "Ifeoluwa Ibraheem", "Ian Kim", "Isabella Kim", "Ilaria Koncius", "Isabella Martinez", "Isabella McPherson", "Isabella Parrent", "Issac Perez", "Isabella Piccirillo", "Ian Shitabata", "Irene Soltani", "Ian Thompsen", "Isabel Zaro"},
	{"Jasmine Alagoz", "Jack Allegaert", "Jacob Ambris", "Jack Balzano", "Joshua Bates", "Joaquin Bejarano", "Jasper Belliveau", "Johanna Berryman", "Jaden Bigley", "Jacob Bobic", "Jack Bowen", "Jaury Burke", "Jaden Camel", "Justin Camel", "Jim Campbell  ", "Justin Campbell", "Jaxon Chang", "Joseph Chelebian", "Joseph Chontos", "Jenna Chow", "Jonathan Chu", "Julia Cohen", "James Cook", "Jack Correa", "Julianna Covarrubias", "Jacob Cutwright", "Jacob Dalis", "Jake Danon", "Jack Davis", "Jessica Delarosa", "Joseph Di Leva", "Jack DiBernardo", "Joshua Diokno  ", "Julian Dixon", "Jack Donell", "Jadon Douglas", "Jared Douglas  ", "Jace Durroh", "Jada Durroh", "Johannes Eberhart", "Jantzen Ebreo", "Jenna Fitzpatrick", "Jack Flanagan", "Jake Fogle", "Jacob Friedman", "Joey Gallardo", "Jenna Gallo", "Jillian Gibson", "John Granick", "Joseph Greger", "Jennifer Grennan", "Jack Griego", "James Happy", "Joseph Hargrove", "John Harris", "Jiale He", "John Helton", "Jordan Hernandez", "Jenna Ho", "Jackson Hodor", "Jason Hong", "Joshua Houlbrooke", "Jeremy Joke", "Jonah Jones", "Joshua Jun", "Joonho Kahng", "John Kahrs", "Jennifer Kamholz", "Jordan Kapner", "Jackson Karlitz", "Joseph Kastelan", "John Klarin", "Juliette Koepke", "Justin Koepke", "Jake Koyama", "Jared Kramer", "Jacqueline Lane", "Jacqueline Lanes", "Jack LaPlant", "Janna Lee", "Jenna Leone", "Jonathan Liu", "Joaquin Lugo", "Jessica Mabry", "Justin Mabry", "John Mac Menamie", "Jessica Majka", "Joze Marinkovic", "Joshua Martin", "Jillian Martz", "Jack Matthews", "John Maurizio", "Jack Mavar", "James Maxwell", "Jake McDonald", "Jackson McKeeve", "Jake Milam", "Joseph Miramontes", "Joelle Montelongo", "Jackson Moore", "Julio Morel", "Joshua Munoz", "Jahzara Nash", "Jordan Nelson", "Jose Ocampo", "John O'Connor", "Joseph O'Connor", "Joshua Ogunkah", "Jessica Ottaway", "John Padian", "Jett Palmer", "John Perry", "Jenna Peterson", "Jennifer Ramirez", "Jacob Reis", "Jason Reyes", "Jason Roah", "Jace Robertson", "Jackson Robertson", "Jamie Robertson", "Jonathan Ross", "Jackson Rucker", "Joseph Ryan", "Juliana Santich", "Joseph Saputo ", "Jonathan Shier", "Jack Simmons", "Jacqueline Skoblar", "Jeremy Smith", "Justin Sohn", "Julia Soll", "Jason Soto  ", "Jake Spivey", "Jonathan Su", "Jiali Sun", "Jingdi Tan", "Jake Tom", "Jack Tomlinson", "Jake Typrowicz", "John Udeani", "Johan Van Wier", "Jace Viramontes", "Julian Wain", "Johanna Walter", "Jonathan Walter", "Jon Ward", "John Warner", "Jadon Watts", "Jake Weyrick", "Jack White", "John Wilhem", "Jaxon Winkler", "Jake Yamane", "Jack Yang", "Jacob Yesnick"},
	{"Kian Alagoz", "Kamal Baker", "Kendall Beshear", "Kaya Bilgic", "Kamran Bottlewalla", "Katelin Campbell", "Kenny Canfield", "Kahealani Carvalho", "Kiana Chang Sigel", "Kevin Chen", "Katherine Choi", "Kale Chominsky", "Kaitlin Cobb", "Kyle Cooper", "Keegan Cross", "Kevin Cross", "Kyleigh Cunningham", "Kate Dean", "Kailey DeHaro", "Kapilaksha Dheeriya", "Kelly Donahue", "Krisan Doshi", "Kayla Epstein", "Kylie Freeland", "Kendall Galosic", "Katherine Gardner", "Kevin Ghaffari", "Kharianna Gracie", "Kaylie Harley", "Katelyn Hart", "Kelsey Hatamiya", "Kayla Hirt", "Kaycee Hong", "Katherine Hoover", "Karen Hori", "Katherine Hoyne", "Keanu Inosanto", "Katherine Jorczak", "Kyle Kan", "Katherine Karmelich", "Kyle Kato", "Konstantine Katona", "Komaljit Kaur", "Kyra Kaya", "Kieran Kearns", "Kiley Keenan", "Katherine Keough", "Kenneth Knapp", "Kiyomi Komatsu", "Kristiana Kovacevic", "Korinna Kuerten", "Kristopher Kuerten", "Kody Lambertus", "Katelynn Lannon", "Kaylin Lee", "Katherine Lewis", "Katelyn Lonas", "Katherine Mandala", "Kristian Masnov", "Kylie McElroy", "Kevin McGibbon", "Kenzi McLay", "Kyla McLay", "Kaia Modica", "Kai Tristan Mohl", "Kylie Mone", "Kate Moore", "Kendra OConnor", "Kevin Rahman", "Kelly Rasmussen", "Katiana Robles", "Kyra Schmid", "Karen Shinzawa", "Kara Shreckengast", "Kate Spaulding", "Katarina Stanojevich", "Kaden Stone", "Kiera Stone", "Kaidan Suh", "Kaitlyn Tarakji", "Kai Teshima", "Kalina Teshima ", "Kayla Thompson", "Koda Torres", "Kelsey Turnbull", "Kaia Van Buren", "Kekoa Van Scoyoc", "Karl Velazquez", "Koa Vetterlein", "Keira Wang", "Karsten Wanke", "Kendall Ward  ", "Kate Warner", "Kylie Welcher", "Kian Woudwijk", "Kiley Wynn"},
	{"Lyndsey Alfaro", "Luka Ardon", "Luke Bejarano", "Lilianne Bohannon", "Liam Bohner", "Leah Buenrostro", "Lauren Chang", "Lucca Chrysostomou", "Lance Cleveland", "Lucas Coleman", "Landon Corman", "Lainey Cote", "Lucas De Leon", "Luca Dileva", "Lauren Eades", "Lucia Eaton", "Lucas Everhart", "Lucas Farrow", "Lauren Feingold", "Leilani Fonoimoana", "Luke Gayton", "Lauren Hammond", "Lily Hamson", "Luke Hassanzai", "Logan Hill", "Luke Hobus", "Lucas Hong", "Lauren Kim", "Lily Kresser", "Lauren Larking", "Lucas Lees", "Luke Leonard", "Leonard Liang", "Lisa Lininger", "Lyuzhi Liu", "Lukas Lizdenis", "Lily Lynch", "Laylah Marron", "Luke Martoccia", "Luka Masnov", "Lucas Mattera", "Laura Maurizio", "Lindsey Metcalfe", "Lisa Miao", "Lauren Naehu", "Luke Nelligan", "Logan Nelson", "Lilly North", "Lucas Odum", "Landon Ota", "Lily Pantoja", "Lauren Peckovich", "Leonardo Puccio", "Luke Rafijah", "Lola Regan", "Luc Rettberg", "Lucia Ruiz", "Lilly Seamans", "Leslie Soriano", "Luke Stefanou", "Luke Stiebel", "Leah Stubblebine", "Lucas Sussman", "Lily Tarica", "Lucas Tharp", "Lauren Thompson", "Lauren Underhill", "Lindsay Yaros   "},
	{"Matthew Abadsantos-Kern", "Melina Acuna", "Markus Aguirre", "Madeleine Ahn", "Michael Artino", "Melina Bakopoulou", "Madalyn Barley", "Matthew Basha", "Maximillian Behzad-Asiri", "Makenna Brannen", "Makayla Brock", "McKenna Butcher", "María Cabanas Zawadzky", "Matthew Carroll", "Matthew Cartmill", "Mia Castillo", "Maxwell Chas", "Mariah Chase", "Michael Clemons", "Mia Colaruotolo", "Maxwell Colomer", "Mafalda Corral", "Macarena Cuesta", "Milo Daluiso", "Michelle Dardon", "Meera David", "Michael Decker", "Madeline Delana", "Mia Dellovade", "Matthew Di Leva", "Meiers Dixon", "Mia Dominguez", "Milad Eghbali", "Myles Elder-Green", "Maximilian Endelman", "Michala Fairchild", "Matthew Farnsworth", "Mathieu Fernandez", "Makena Fine", "Mia Fitzpatrick  ", "Matthew Francis", "Mily Frazier", "Morgan Fresch", "Matthew Frey", "Maddox Gamble", "Madison Grant", "MacKenzie Gregory", "Mark Guggenheim", "Michael Guirgis", "Mia Harley", "Melanie Harris", "Myles Hasegawa", "Meagan Hendershot", "Milana Herrera", "Miles Hong", "Mackenzie Huff", "Maleha Innocent", "Makena Irvine", "Morgan Irvine", "Mason Jahelka", "Mason Jones", "Matthew Kang", "Minji Kang", "Mischa Kharrazi", "Megan Kinsolving", "Michael Kwon", "Mackenzie Lambertus", "Maxwell Larkin", "Mark Lee", "Max Leeds", "Matthew Liang", "Mark Lin", "Marina Lugliani", "Michael Mackiewicz", "Matthew Madrid", "Matthew Maes", "Michael Malone", "Mia Marco", "Maximillian Marohn", "Michael McBride", "Mia McCauley", "Margaret McLeod", "Makayla McNeill", "Max Mendel", "Maya Merchant", "Maxwell Merritt", "Mallory Meyer", "Matthew Mihelich", "Madison Miller", "Michael Mitsanas", "Matthew Morachis", "Maya Munoz", "Michael Nagy", "Marko Nikoletic", "Megan O'Brien", "Megan Ocasio", "Margaret O'Hern", "McKenzie Olsen", "Matthew Olson", "Marinna Pisano", "Mykiah Plummer", "Mateo Poncia", "Marco Popovich", "Maggie Puhl", "Matthew Rafter", "Michael Rafter", "Marco Rall Boardman", "Maja Rancic", "Maya Roberson", "Mario Rodriguez Mendez", "Maya Rosales", "Maya Sanacore", "Marielle Sandler", "Marjorie Say  ", "Martin Scholz", "Mason Self", "Mackenzie Shannon", "Madeline Smith", "Mikayla Smith", "Melody Soroosh", "Michael Sprengel", "Mark Steburg", "Madeline Steinbach", "Morgan Tomaro", "Megan Trainotti", "Michael Tuberosi", "Mia Vafadari", "Matthew Valero", "Matias Wahlstrom", "Megan Walsh", "Matthew Warter", "Madeline Weatherly", "Madison Wendel", "Maya Whitcomb", "Megan White", "Mackenzie Whitehead", "Mikayla Wurzer", "Matthias Yee", "Matthew Yoon", "Meg Yoshida", "Maxwell Zarchy"},
	{"Niko Adoric", "Nilaab Ahmadi", "Natalie Andersson", "Nicholas Baumann", "Nathan Blakey", "Nicholas Bozanic", "Nolan Brandt", "Natalie Castro", "Nadia Cerda", "Nathan Chavira", "Natalie Chrone", "Nicole Chung", "Niall Collins", "Nicholas Cosgrove", "Neela David", "Natalie Diaz", "Nathan Dimacali", "Nation Dixon", "Nicholas Esposito", "Natalie Ferin Tholan", "Nicholas Finazzo", "Naomi Gan", "Noah Garcia", "Nicholas Gruninger", "Nathan Harper", "Nicholas Headon", "Nicholas Hirt", "Natalie Hong", "Natalia Huntington", "Nima Izadi", "Nicole Jo", "Nolan Kalty", "Naomi Kao", "Nathan Khalil", "Nathan Kim", "Nefise Kocak", "Noah Lin", "Nicole Liontos", "Nathaly Lizarraga", "Nico Lofty", "Nathan Madani", "Nevin Mann", "Nicholas Mantikas", "Nikolaos Mantikas", "Noor Mathew", "Nicholas Michaels", "Nathanael Nam", "Natasha Nirmal", "Nate Nordine", "Nikolas Pasquariello", "Natalia Pope", "Nicole Rasmussen", "Nathan Reinhart", "Natalie Reyes", "Noemi Ruelas ", "Nikole Rugnetta   ", "Nicole Russo", "Nicolas Sanchez", "Nicholas Semmer", "Noah Simpson", "Natalee Soroosh", "Natasha Stein", "Nathan Stein", "Nicholas Stiebel", "Natalie Stubblebine", "Nika Susnjar", "Nikita Swatek", "Nikolas Tsangaris", "Nicholas Ungaro", "Nicholas Vodanovich", "Noah Wahl", "Natalie Wang", "Nina Whitcomb", "Nicolas Wright", "Nathan Yakubik", "Natalie Ying"},
	{"Owen Brown", "Owen Chas", "Owen Cuyler", "Owen Griffiths", "Olivia Hamilton", "Olivia Hecker", "Owen Hong", "Omeed Jahromi", "Oliver Knotek", "Owen Ladinig", "Olivia Malit", "Olivia McPhee", "Oscar Park", "Owen Park", "Owen Sanford", "Olivia Schnel", "Owen Traina", "Olivia Tuberosi"},
	{"Payton Ahn", "Paolo Bahrami", "Paolo Brinderson", "Peyton Brusick", "Patricio Cabagna", "Peter Chang", "Paris Dunlavey", "Peyton Eberhard", "Parker Evans", "Paige Forte", "Paige Foster", "Parker Fry", "Patrick Hwang", "Priscilla Kim", "Peter Kraemer", "Pili Marco", "Philip Melcic", "Paris Miller", "Peter Mirich", "Pierce O'Leary", "Paige Porter", "Polly Power", "Petra Riggs", "Paige Roach", "Patrick Robles", "Patrick Roche", "Parham Seyedshakeri   ", "Paige Shin", "Phillipe Wiederkehr", "Parker Zane"},
	{"Quinn McLean", "Quentin Ruiz "},
	{"Ricardo Alexander", "Rachel Allen", "Ryan Anderson", "Rebecca Aycock", "Ryan Baeza", "Rodrigo Boixo Fernandez De La Cigona  ", "Rachel Bond", "Rhett Borda", "Ross Borden", "Ryan Bozanic", "Ryan Choi", "Richard Criley", "Ra'nya Crowder", "Rayanne Fadich", "Rose Feng", "Ryan Foley", "Ryan Fuerte", "Rocco Gambino", "Raquel Gastelum", "Radin Ghamari", "Rohan Gianchandani", "Rayan Hashemy", "Rhys Hendershot", "Reed Herendeen", "Ryan Hetchler", "Robert Higgins", "Ryan Hori", "Rudi Johnson", "Rebecca Kim", "Rowan Klein", "Ryan Klibanov", "Riley Lampe", "Renee Lee", "Reese Levendusky", "Ryann Levendusky", "Rui Xian Ransom Liu", "Rachael Lockwood", "Ronald Lockwood", "Riley Maguire", "Robert Marshall", "Rosemary Martin", "Rider Mavar", "Rachel McGinty", "Ryan Mendez", "Raymond Moll", "Rowan Moore", "Rhyan Nguyen", "Ryan Nguyen", "Ryan Olarte", "Rebecca Olvera", "Riley Padian", "Rachel Post", "Robert Ranaldi", "Royce Relatores", "Rylee Ricard", "Ryan Roche", "Ryan Samani", "Ryan Schilling", "Riley Skinner", "Rei Takarai", "Roslyn Tauvaa", "Reese Tillson", "Ripley Uyeda", "Rayna Volman", "Ronan Volman", "Rylee Wahl  ", "Randall Wilson", "Ryan Wilson"},
	{"Sophia Aguirre", "Shea Albano", "Shayli Atashi", "Sarah Austin", "Scarlet Bailey", "Sydney Baker", "Sofia Bandy", "Sagan Barbour", "Sydni Bednarek", "Samuel Bonner", "Sophia Brborich", "Sebastian Burns", "Stuart Canario", "Sarah Cartmill", "Stephanie Cathcart", "Sienna Ceja", "Sasha Chehrzadeh", "Samantha Chelf", "Stuart Clements", "Sophia Cline", "Sean Conlon", "Sean Cosgrove", "Sanai Cunningham", "Sophia Cuyler", "Sofia Daneshvar", "Shay Desai", "Sedona Ding", "Stefan Dreer", "Stephen DuVernet", "Sienna Elkin", "Sabrina Fair", "Sean Faris", "Sofia Fasoletti", "Sofia Fateeva", "Sydnie Fuchs", "Sophie Geniesse", "Sarah Giller", "Sydney Goodrich", "Samuel Green", "Sean Halligan", "Sophie Ray Harrah", "Sasha Hayes-Pleasant", "Sean Hetrick", "Suzanne Jellison", "Sang Hee Jun", "Sarah Jun", "Sofia Kalem", "Stephen Kastelan", "Sofia Katzaroff", "Steven Kaufman", "Sarah Keller", "Sihoon Kim", "Samantha Laurin", "Samantha Lekawa", "Shay Lennemann", "Shaun Leone", "Spencer Levin", "Samuel Levine", "Sarah Liu", "Sydney Lyle", "Shannon Lynch", "Sophia MacAller", "Spencer MacLeay", "Sam Malekzadeh", "Stella McKay", "Sydney Merchant", "Sara Metcalfe", "Samuel Miller", "Suhayb Mirza", "Sharlize Moayedi", "Shaya Moayedi", "Samuel Moore", "Saul Munn", "Steven Nagy", "Sierra Namvari", "Sydney Naya", "Sophia Norris", "Simone Ochalek", "Sarah Park", "Savannah Peden", "Skye Perez", "Savanna Pierson", "Shelby Ponce", "Sophia Potter", "Stephanie Prado", "Shawnee Prieto", "Sarah Rancic", "Sophia Rodriguez", "Samuel Rohde", "Samuel Rokaw", "Sofiya Ruban", "Sharlena Sarmast", "Sebastian Schoepke", "Sarah Shah", "Sky Shaw", "Scott Shimoyama", "Sara Silvestri", "Sayan Simanian", "Sarah Simon", "Sydney Singh", "Samantha Skeoch", "Sean Slingsby", "Sierra Smith ", "Skyler Snakenborg", "Siena Snure", "Shalomiel Solel", "Shon Stallings", "Sophia Stoddart", "Sharon Stoy", "Skylor Sun", "Sophie Sun", "Sophie Tangalakis", "Sophia Ticknor", "Siena Tomasevich", "Stone Townley", "Salvatore Traina", "Spencer Tran", "Sophia Wattson", "Steel Weiss", "Sean Winbush", "Sofia Yarymovych", "Sofia Zavarella   "},
	{"Tarick Ahmed", "Ty Arvizo", "Tyler Bagley", "Trace Basich", "Tara Bharadia", "Talia Blair", "Troy Burad", "Tony Califano", "Tyler Campbell", "Tony Cha", "Tiffany Chang", "Tyler Colaruotolo", "Tingyi Cui", "Tessa Dontscheff", "Tristan Drake", "Tyler Ewald", "Tara Fermanian", "Tor Gasteiger", "Trent Giacalone", "Tyler Gonnerman", "Tatiana Grimes", "Talon Gutierrez", "Toni Hagan", "Tate Hajek", "Talia Hajjar", "Talia Herniter", "Taylor Hirsch", "Timothy Keroles", "Teh-Han Kim", "Tom Kim", "Thomas Kraak", "Tatum Lane", "Thomas LaPine", "Thomas Lee", "Timothy Lee", "Thomas Lercari", "Tatiana Lindahl", "Tyler Ljubic", "Tara Lofty", "Tyler Madani", "Taylor Malinofsky", "Tiana Mann", "Thomas Manth", "Tali McLay", "Tristan Messerli", "Tyler Morales", "Talia Patti", "Tate Rioux", "Tobias Rodriguez", "Triston Rose", "Tatiana Rosenfield", "Tyler Royes", "Theodore Schipper  ", "Trevor Seaburn", "Trystan Sheldon", "Ty Sorenson", "Tomoi Stapleton", "Toby Stoler", "Taylor Stroud", "Troy Takahashi", "Tyler Tellenbach", "Thomas Tetreault", "Thomas Underhill", "Terra Van Dine", "Tristan Wattson", "Taj Whitehead"},
	{},
	{"Vanya Agrawal", "Vance Arenstein", "Van Borda", "Vivian Chan", "Vincent Chor", "Vikesh Dheeriya", "Valentina Duran Oris De Roa", "Violet Fermanian", "Vincent Furriel", "Valentina Gardner", "Vanessa Geich", "Viviana Hsiao", "Vaughn Kissel", "Victoria Messano", "Victoria Moll", "Victoria Nolan", "Violet Peer", "Vidyuth Thattai", "Vanessa Tran", "Vince Villasenor", "Vytautas Vitkus", "Victoria Vodanovich", "Veronica Waters"},
	{"Willis Alalou", "William Bengston", "Westley Brannan", "William Bray", "William Corry", "Williams Criley", "William Engstrom", "William Gray", "William Hall", "William Hirai", "Westley Johnson", "William Jorczak", "William Kirchofer", "William Kirk", "William Lyle", "William Mulkey", "William Patel", "William Perry", "William Rizzo", "William Sasaki     ", "William Smart", "Whitney Todosiev", "William (Ryan) Um", "Wyatt Vyce", "William Welsh", "Willow Wollman", "Wylder Wollman  ", "William Wong"},
	{"Xander Chang", "XinYue Sun"},
	{"Ysabelle AbadSantos-Kern", "Yongqi Shen", "Yoonseo Yi"},
	{"Zacharia Ahmadi", "Zoey Belliveau", "Zachary Dawson", "Zoe Dearborn", "Zusan Hu", "Zachary Huang", "Zoe Hutchins", "Zane Johnson", "Zachary Kakazu", "Zoe Klein", "Zhengjie Li", "Zachary Moore", "Zachary Pearce", "Zoe Ruehr", "Zachary Schmidt  ", "Zoe Shafiezadeh  ", "Zoe Shippee  ", "Zackary Smith", "Zen Vibhakar", "Zander Zupon"}
};

vector<string> getNames(string list) { //separates all the names from each other

    vector<string> names = {};
    string currentName = "";
    for(int i = 0; i < list.size(); i++) {
        if(list.at(i) == ',' || list.at(i) == ':') {
            names.push_back(currentName);
            currentName = "";
            i++;
        }
        else if(list.at(i) == '.' && !(currentName == "Mr" || currentName == "Mrs" || currentName == "Ms")) {
            names.push_back(currentName);
            currentName = "";
            i++;
        }
        else
            currentName += list.at(i);
    }
    names.push_back(currentName);

    return names;

}

void checkSpelling(vector<string> names) { //compares each name to the names in the database

    cout << "Wrong Names:" << endl;
    for(int i = 0; i < names.size(); i++) {

        string currentName = names.at(i);
        int firstLetter = (int)(currentName.at(0));
        if(firstLetter < 97)
            firstLetter -= 65;
        else
            firstLetter -= 97;

        if(firstLetter < 26) {

            bool nameFound = false;
            for(int j = 0; j < nameDB[firstLetter].size(); j++) {
                if(currentName == nameDB[firstLetter][j]) {
                    nameFound = true;
                    break;
                }
            }
            if(!nameFound)
                cout << currentName << endl;

        }

    }
    cout << "\n";

}

int main() { //driver

    string list;
    while(true) {
        cout << "Input names separated by commas:\n";
        getline(cin, list);
        vector<string> names = getNames(list);
        checkSpelling(names);
    }

    /*for(int i = 0; i < names.size(); i++) {
        cout << names.at(i) << endl;
    }*/

}